/**
 * Line 1 baseline queue for plant demo (BFF + MSW).
 * Generated by cursor/scripts/generate-pasco-plant-demo-queue.mjs — do not edit by hand.
 * Sources: lsv_line_1.csv (LSVLN1 NEW), sap_order_headers / pass_fail for demo anchors.
 */

import type { QueueRow } from './plantDemoTypes';

export const PASCO_LINE1_BASELINE: QueueRow[] = [
  { po: '1001759341', species: 'SWCO', kg: 4200, finish: '2026-07-04 11:30', status: 'PLANNED' },
  { po: '1001884747', species: 'SWCO', kg: 9800, finish: '2026-07-05 16:00', status: 'PLANNED', atRisk: true, reasonShort: 'SAP due date — monitor slot' },
  { po: '1002307551', species: 'SWCO', kg: 6400, finish: '2026-07-06 09:00', status: 'PLANNED', atRisk: true, reasonShort: 'Priority 2 — customer window' },
  { po: '1002266913', species: 'PECO', kg: 164940, finish: '2026-07-07 10:00', status: 'PLANNED' },
  { po: '1002267630', species: 'PECO', kg: 56170, finish: '2026-07-07 14:00', status: 'PLANNED' },
  { po: '1002174855', species: 'SWCO', kg: 48400, finish: '2026-07-07 16:00', status: 'PLANNED' },
  { po: '1002181889', species: 'SWCO', kg: 42000, finish: '2026-07-08 10:00', status: 'PLANNED' },
  { po: '1002266889', species: 'PECO', kg: 36310, finish: '2026-07-08 14:00', status: 'PLANNED' },
  { po: '1002266886', species: 'PECO', kg: 35230, finish: '2026-07-08 16:00', status: 'PLANNED' },
  { po: '1002295415', species: 'SWCO', kg: 24610, finish: '2026-07-09 10:00', status: 'PLANNED' },
  { po: '1002307552', species: 'SWCO', kg: 24500, finish: '2026-07-09 14:00', status: 'PLANNED' },
  { po: '1002266351', species: 'PECO', kg: 23170, finish: '2026-07-09 16:00', status: 'PLANNED' },
  { po: '1002150398', species: 'SWCO', kg: 16400, finish: '2026-07-10 10:00', status: 'PLANNED' },
  { po: '1002266356', species: 'PECO', kg: 14930, finish: '2026-07-10 14:00', status: 'PLANNED' },
  { po: '1002295402', species: 'SWCO', kg: 14186, finish: '2026-07-10 16:00', status: 'PLANNED' },
  { po: '1002266350', species: 'PECO', kg: 3390, finish: '2026-07-11 10:00', status: 'PLANNED' },
  { po: '1002302916', species: 'SWBS', kg: 698, finish: '2026-07-11 14:00', status: 'PLANNED' },
  { po: '1001887703', species: 'SWCO', kg: 18537, finish: '2026-06-30 08:00', status: 'COMPLETE' },
];
