/**
 * Line 1 baseline queue for plant demo (BFF + MSW).
 * Generated by cursor/scripts/generate-pasco-plant-demo-queue.mjs — do not edit by hand.
 * Sources: main.csv (LSVLN1 NEW), line_1_schedule.csv (INT Ln1 backlog), demo anchors.
 */

import type { QueueRow } from './plantDemoTypes';

export const PASCO_LINE1_BASELINE: QueueRow[] = [
  { po: '1001759341', species: 'SWCO', kg: 4200, finish: '2026-07-04 11:30', status: 'PLANNED' },
  { po: '1001884747', species: 'SWCO', kg: 9800, finish: '2026-07-05 16:00', status: 'PLANNED', atRisk: true, reasonShort: 'SAP due date — monitor slot', customerOrderId: 'CO-44102' },
  { po: '1001883359', species: 'SWCO', kg: 50852, finish: '2026-07-05 18:00', status: 'PLANNED', reasonShort: 'On plan — alternate QA script B' },
  { po: '1002307551', species: 'SWCO', kg: 6400, finish: '2026-07-06 09:00', status: 'PLANNED', atRisk: true, reasonShort: 'Priority 2 — customer window', customerOrderId: 'CO-44821' },
  { po: '1002266913', species: 'PECO', kg: 164940, finish: '2026-07-07 10:00', status: 'PLANNED' },
  { po: '1002051116', species: 'SWCO', kg: 105666, finish: '2026-07-07 14:00', status: 'PLANNED' },
  { po: '1002178923', species: 'SWCO', kg: 82570, finish: '2026-07-07 16:00', status: 'PLANNED' },
  { po: '1002037158', species: 'SWCO', kg: 75036, finish: '2026-07-08 10:00', status: 'PLANNED' },
  { po: '1002051115', species: 'SWCO', kg: 69156, finish: '2026-07-08 14:00', status: 'PLANNED' },
  { po: '1002150406', species: 'SWCO', kg: 57174, finish: '2026-07-08 16:00', status: 'PLANNED' },
  { po: '1002267630', species: 'PECO', kg: 56170, finish: '2026-07-09 10:00', status: 'PLANNED' },
  { po: '1002183878', species: 'SWCO', kg: 56039, finish: '2026-07-09 14:00', status: 'PLANNED' },
  { po: '1002045031', species: 'SWCO', kg: 51234, finish: '2026-07-09 16:00', status: 'PLANNED' },
  { po: '1002183877', species: 'SWCO', kg: 50106, finish: '2026-07-10 10:00', status: 'PLANNED' },
  { po: '1002174855', species: 'SWCO', kg: 48400, finish: '2026-07-10 14:00', status: 'PLANNED' },
  { po: '1002178987', species: 'SWCO', kg: 44335, finish: '2026-07-10 16:00', status: 'PLANNED' },
  { po: '1002181889', species: 'SWCO', kg: 42604, finish: '2026-07-11 10:00', status: 'PLANNED' },
  { po: '1002031743', species: 'SWCO', kg: 38060, finish: '2026-07-11 14:00', status: 'PLANNED' },
  { po: '1002183876', species: 'SWCO', kg: 37717, finish: '2026-07-11 16:00', status: 'PLANNED' },
  { po: '1002177346', species: 'SWCO', kg: 36652, finish: '2026-07-12 10:00', status: 'PLANNED' },
  { po: '1002266889', species: 'PECO', kg: 36310, finish: '2026-07-12 14:00', status: 'PLANNED' },
  { po: '1002170965', species: 'SWCO', kg: 35966, finish: '2026-07-12 16:00', status: 'PLANNED' },
  { po: '1002043950', species: 'SWCO', kg: 35950, finish: '2026-07-13 10:00', status: 'PLANNED' },
  { po: '1002181891', species: 'SWCO', kg: 35351, finish: '2026-07-13 14:00', status: 'PLANNED' },
  { po: '1002266886', species: 'PECO', kg: 35230, finish: '2026-07-13 16:00', status: 'PLANNED' },
  { po: '1002038692', species: 'SWCO', kg: 33746, finish: '2026-07-14 10:00', status: 'PLANNED' },
  { po: '1002150408', species: 'SWCO', kg: 33613, finish: '2026-07-14 14:00', status: 'PLANNED' },
  { po: '1002178919', species: 'SWCO', kg: 29000, finish: '2026-07-14 16:00', status: 'PLANNED' },
  { po: '1002180618', species: 'SWCO', kg: 27786, finish: '2026-07-15 10:00', status: 'PLANNED' },
  { po: '1002173595', species: 'SWCO', kg: 27532, finish: '2026-07-15 14:00', status: 'PLANNED' },
  { po: '1002045029', species: 'SWCO', kg: 27299, finish: '2026-07-15 16:00', status: 'PLANNED' },
  { po: '1002036812', species: 'SWCO', kg: 27142, finish: '2026-07-16 10:00', status: 'PLANNED' },
  { po: '1002150145', species: 'SWCO', kg: 26728, finish: '2026-07-16 14:00', status: 'PLANNED' },
  { po: '1002150403', species: 'SWCO', kg: 26538, finish: '2026-07-16 16:00', status: 'PLANNED' },
  { po: '1002181740', species: 'SWCO', kg: 25780, finish: '2026-07-17 10:00', status: 'PLANNED' },
  { po: '1002177224', species: 'SWCO', kg: 25549, finish: '2026-07-17 14:00', status: 'PLANNED' },
  { po: '1001887703', species: 'SWCO', kg: 18537, finish: '2026-06-30 08:00', status: 'COMPLETE' },
];
